# Generated by Django 3.2.11 on 2022-05-27 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField(default=0.0)),
                ('crypto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crypto.crypto')),
            ],
        ),
        migrations.CreateModel(
            name='Felling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('felling', models.FloatField(default=0.0)),
                ('crypto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crypto.crypto')),
            ],
        ),
    ]
