# Generated by Django 3.2.11 on 2022-06-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='link',
            field=models.TextField(),
        ),
    ]
