# Generated by Django 3.2.11 on 2022-05-27 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_felling_pricerecord'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Felling',
            new_name='Sentiment',
        ),
    ]
