# Generated by Django 3.2.11 on 2022-05-28 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_sentiment_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentiment',
            old_name='felling',
            new_name='sentiment',
        ),
    ]
