# Generated by Django 3.2.11 on 2022-05-29 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ners', models.TextField()),
                ('fre', models.TextField()),
                ('sentiment', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('symbol', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='PriceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField(default=0.0)),
                ('crypto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crypto.crypto')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sentiment', models.FloatField(default=0.0)),
                ('crypto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crypto.crypto')),
                ('price', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crypto.pricerecord')),
            ],
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('link', models.URLField()),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto.analisis')),
                ('crypto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crypto.crypto')),
                ('sentiment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crypto.sentiment')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto.source')),
            ],
        ),
    ]
