# Generated by Django 3.2.11 on 2022-05-27 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crypto', '0002_felling_pricerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ners', models.TextField()),
                ('fre', models.TextField()),
                ('sentiment', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(max_length=128)),
                ('link', models.URLField()),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.analisis')),
                ('crypto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crypto.crypto')),
            ],
        ),
    ]
