# Generated by Django 3.2.11 on 2022-05-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisis',
            name='sentiment',
            field=models.FloatField(default=0),
        ),
    ]
