# Generated by Django 3.2.11 on 2022-08-04 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ners', models.TextField()),
                ('fre', models.TextField()),
                ('sentiment', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sentiment', models.FloatField(default=0.0)),
                ('crypto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crypto.crypto')),
                ('price', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crypto.pricerecord')),
            ],
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('link', models.TextField()),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.analisis')),
                ('crypto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crypto.crypto')),
                ('sentiment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='news.sentiment')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.source')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
