
version: '3'

services:
  db:
    image: mysql
    #restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: hernanborre
      MYSQL_USER: dev
      MYSQL_PASSWORD: hernanborre
      MYSQL_DATABASE: dev

  api_web:
    build: .
    tty: true
    #restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./envs/db.env
    depends_on:
      - db
